# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 16:49
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import finance.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('price', finance.models.MoneyField(decimal_places=8, default=Decimal('0'), max_digits=23)),
                ('amount', finance.models.MoneyField(decimal_places=8, default=Decimal('0'), max_digits=23)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cancel Order',
                'verbose_name_plural': 'Cancel Orders',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50, unique=True)),
                ('short_name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('sign', models.CharField(max_length=3, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', finance.models.MoneyField(decimal_places=8, default=Decimal('0'), max_digits=23, validators=[finance.models.MoneyMinValueValidator()])),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deposit',
                'verbose_name_plural': 'Deposits',
            },
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('price', finance.models.MoneyField(decimal_places=8, default=Decimal('0'), max_digits=23)),
                ('amount', finance.models.MoneyField(decimal_places=8, default=Decimal('0'), max_digits=23)),
                ('fee', finance.models.MoneyField(decimal_places=8, default=Decimal('0'), max_digits=23)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exchange',
                'verbose_name_plural': 'Exchanges',
            },
        ),
        migrations.CreateModel(
            name='ExchangeCandle5Min',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('is_grow', models.BooleanField()),
                ('price_open', finance.models.MoneyField(decimal_places=8, default=Decimal('0'), max_digits=23)),
                ('price_close', finance.models.MoneyField(decimal_places=8, default=Decimal('0'), max_digits=23)),
                ('price_min', finance.models.MoneyField(decimal_places=8, default=Decimal('0'), max_digits=23)),
                ('price_max', finance.models.MoneyField(decimal_places=8, default=Decimal('0'), max_digits=23)),
            ],
            options={
                'verbose_name': 'ExchangeCandle5Min',
                'verbose_name_plural': 'ExchangeCandle5Mins',
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('operation_type', models.CharField(max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': 'Journals',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type', models.IntegerField(choices=[(1, 'sell'), (2, 'buy')], db_index=True)),
                ('status', models.IntegerField(choices=[(1, 'active'), (2, 'cancelled'), (3, 'done')], db_index=True, default=1)),
                ('priority', models.IntegerField(db_index=True, default=0)),
                ('price', finance.models.MoneyField(db_index=True, decimal_places=8, default=Decimal('0'), max_digits=23, validators=[finance.models.MoneyMinValueValidator()])),
                ('fee', finance.models.MoneyField(decimal_places=8, default=Decimal('0'), editable=False, max_digits=23)),
                ('amount', finance.models.MoneyField(decimal_places=8, default=Decimal('0'), max_digits=23, validators=[finance.models.MoneyMinValueValidator()])),
                ('amount_stock', finance.models.MoneyField(decimal_places=8, default=Decimal('0'), editable=False, max_digits=23)),
                ('wallet_reserve', finance.models.MoneyField(decimal_places=8, default=Decimal('0'), editable=False, max_digits=23)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('journal', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='finance.Journal')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderMotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', finance.models.MoneyField(decimal_places=8, default=Decimal('0'), max_digits=23)),
                ('amount_end', finance.models.MoneyField(decimal_places=8, default=Decimal('0'), max_digits=23)),
                ('wallet_reserve', finance.models.MoneyField(decimal_places=8, default=Decimal('0'), max_digits=23)),
                ('wallet_reserve_end', finance.models.MoneyField(decimal_places=8, default=Decimal('0'), max_digits=23)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Journal')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Order')),
            ],
            options={
                'verbose_name': 'OrderMotion',
                'verbose_name_plural': 'OrderMotions',
            },
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, editable=False, max_length=100, unique=True)),
                ('fee', finance.models.MoneyField(decimal_places=8, default=Decimal('0.00200000000000000004163336342344337026588618755340576171875'), max_digits=23)),
                ('active', models.BooleanField(default=True)),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('currency1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_currency1', to='finance.Currency')),
                ('currency2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_currency2', to='finance.Currency')),
            ],
            options={
                'verbose_name': 'Pair',
                'verbose_name_plural': 'Pairs',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=50)),
                ('balance', finance.models.MoneyField(decimal_places=8, default=Decimal('0'), editable=False, max_digits=23)),
                ('balance_reserve', finance.models.MoneyField(decimal_places=8, default=Decimal('0'), editable=False, max_digits=23)),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Currency')),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
        migrations.CreateModel(
            name='WalletMotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(default=0)),
                ('balance', finance.models.MoneyField(decimal_places=8, default=Decimal('0'), max_digits=23)),
                ('balance_end', finance.models.MoneyField(decimal_places=8, default=Decimal('0'), max_digits=23)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Journal')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Wallet')),
            ],
            options={
                'verbose_name': 'WalletMotion',
                'verbose_name_plural': 'WalletMotions',
            },
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', finance.models.MoneyField(decimal_places=8, default=Decimal('0'), max_digits=23)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Currency')),
                ('journal', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='finance.Journal')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Wallet')),
            ],
            options={
                'verbose_name': 'Withdraw',
                'verbose_name_plural': 'Withdraws',
            },
        ),
        migrations.CreateModel(
            name='WithdrawRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.IntegerField(choices=[(1, 'new'), (2, 'approved'), (3, 'refused')], default=1)),
                ('amount', finance.models.MoneyField(decimal_places=8, default=Decimal('0'), max_digits=23)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Currency')),
                ('journal', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='finance.Journal')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Wallet')),
            ],
            options={
                'verbose_name': 'WithdrawRequest',
                'verbose_name_plural': 'WithdrawRequests',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Pair'),
        ),
        migrations.AddField(
            model_name='order',
            name='wallet_in',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='order_wallet_in', to='finance.Wallet'),
        ),
        migrations.AddField(
            model_name='order',
            name='wallet_out',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='order_wallet_out', to='finance.Wallet'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='journal',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='finance.Journal'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='order_buy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_order_buy', to='finance.Order'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='order_sell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_order_sell', to='finance.Order'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Pair'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deposit',
            name='journal',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='finance.Journal'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Wallet'),
        ),
        migrations.AddField(
            model_name='cancelorder',
            name='journal',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='finance.Journal'),
        ),
        migrations.AddField(
            model_name='cancelorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Order'),
        ),
        migrations.AddField(
            model_name='cancelorder',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Wallet'),
        ),
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together=set([('client', 'currency')]),
        ),
    ]
