# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='code',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pair',
            name='id',
        ),
        migrations.AlterField(
            model_name='currency',
            name='short_name',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pair',
            name='name',
            field=models.CharField(editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
