# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 12:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
