# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20160506_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=120, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='admin access'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=120, verbose_name='Last name'),
        ),
    ]
