# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 11:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20160511_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=120, verbose_name='First name')),
                ('last_name', models.CharField(max_length=120, verbose_name='Last name')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='datetimeformat',
            field=models.CharField(default='yyyy-MM-dd hh:mm:ss', max_length=30, verbose_name='Dateformat'),
        ),
        migrations.AddField(
            model_name='client',
            name='is_email_confirmed',
            field=models.BooleanField(default=False, verbose_name='email confirmed'),
        ),
        migrations.AddField(
            model_name='client',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian')], default='en', max_length=2, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='client',
            name='timezone',
            field=models.CharField(max_length=30, null=True, verbose_name='Timezone'),
        ),
    ]
